### ISSUE TITLE
[Question] Hitch Game

### ISSUE THREAD

**Issue by flcreations** [Andriamanitra/andriamanitra.github.io#1]
Hey Andriamanitra,
you made that interesting hitchhiking game. I was wondering if I could use your assets & code to make an Android version from it. You will be of course credited for that.
Thanks.

There's a sneak preview (it works excellently on Android)
![1](https://user-images.githubusercontent.com/52599473/61547320-70029f80-aa4b-11e9-890d-db0630cb9942.png)
![2](https://user-images.githubusercontent.com/52599473/61547319-70029f80-aa4b-11e9-98c0-e671f73e4ba3.png)

**Comment by Andriamanitra** [comment]
Sure - as per the [license](https://github.com/Andriamanitra/andriamanitra.github.io/blob/master/UNLICENSE) you're free to use/modify all of my code and assets however you like!
